version: '3'

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: bataille
            MYSQL_DATABASE: bataille
            MYSQL_USER: bataille
            MYSQL_PASSWORD: bataille
        ports:
            - "9906:3306"
    web:
        image: php:7.2.2-apache
        container_name: bataille_php
        depends_on:
            - db
        volumes:
            - ./code/:/var/www/html/
        ports:
            - "8000:80"
        stdin_open: true
        tty: true