version: '3'

services:
    web:
        image: php:8.0-apache
        container_name: bataille_php
        volumes:
            - ./src/:/var/www/html/
        ports:
            - "8000:80"
        stdin_open: true
        tty: true